"""
Django settings for home project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

from .settings import *

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DATABASE_NAME', 'test'),
        'USER': os.environ.get('DATABASE_USER', 'test'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD', 'test'),
        'HOST': os.environ.get('DATABASE_HOST', '127.0.0.1'),
        'PORT':  os.environ.get('DATABASE_PORT', '5432'),
    }
}
