# Generated by Django 2.2 on 2019-10-04 17:31

import os
from django.db import migrations
from django.conf import settings
from django.core import serializers


def load_fixture(apps, schema_editor):
    fixture_file = os.path.join(settings.BASE_DIR, 'apartment.json')
    fixture = open(fixture_file)
    objects = serializers.deserialize('json', fixture, ignorenonexistent=True)
    for obj in objects:
        obj.save()
    fixture.close()


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture)
    ]
